Update android-ci.yml

diff --git a/.github/workflows/android-ci.yml b/.github/workflows/android-ci.yml
--- a/.github/workflows/android-ci.yml
+++ b/.github/workflows/android-ci.yml
@@ -1,79 +1,108 @@
-# Workflow name
-name: Release App
+name: Build and Release APK
 
-# When it will be triggered
 on:
   push:
     branches:
-      - main
+      - master # Change this to your main branch
 
-# Where it will run
 jobs:
-  build:
+  check_secrets:
     runs-on: ubuntu-latest
 
-- name: Fetch Sources
-  uses: actions/checkout@v2
-  with:
-    # Number of commits to fetch. 0 indicates all history for all branches and tags.
-    fetch-depth: 0
+    steps:
+    - name: Check GitHub Secrets
+      run: |
+        if [ -z "${{ secrets.KEYSTORE_FILE }}" ]; then
+          echo "Missing KEYSTORE_FILE secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
+          echo "Missing KEYSTORE_PASSWORD secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
+          echo "Missing KEY_ALIAS secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
+          echo "Missing KEY_PASSWORD secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.MAP_URL }}" ]; then
+          echo "Missing MAP_URL secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+          echo "Missing GITHUB_TOKEN secret"
+          exit 1
+        fi
+        if [ -z "${{ secrets.APP_NAME }}" ]; then
+          echo "Missing APP_NAME secret"
+          exit 1
+        fi
 
-- name: Setup JDK
-  uses: actions/setup-java@v2
-  with:
-    distribution: 'zulu'
-    java-version: '11'
+  build:
+    needs: check_secrets
+    runs-on: ubuntu-latest
 
-- name: Setup Android SDK
-  uses: android-actions/setup-android@v2
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-# Cache Gradle dependencies and Gradle Wrapper
-- name: Setup Gradle Cache
-  uses: actions/cache@v2
-  with:
-    path: |
-      ~/.gradle/caches
-      ~/.gradle/wrapper
-    key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
+    - name: Set up JDK
+      uses: actions/setup-java@v2
+      with:
+        distribution: 'adopt'
+        java-version: '17'
+   
+    - name: Restore keystore from secret
+      run: echo "${{ secrets.KEYSTORE_FILE }}" | tr -d '\n' | base64 -d > /home/runner/work/reactmap-android/reactmap-android/keystore.jks
+    
+    - name: Check if keystore is available
+      run: ls -a /home/runner/work/reactmap-android/reactmap-android/keystore.jks
 
-- name: Make gradlew executable
-  run: chmod +x ./gradlew
+    - name: Make Gradlew executable
+      run: chmod +x ./gradlew
+    
+    - name: Extract versionName from gradle.properties
+      id: extract_version
+      run: echo "VERSION_NAME=$(grep 'reactmap.versionName' gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
 
-- name: Generate App Version Name
-   run: echo "VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')" >> $GITHUB_ENV
+    - name: Set Package Name
+      run: echo "PACKAGE_NAME=${{ secrets.PACKAGE_NAME || 'be.mygod.reactmap' }}" >> $GITHUB_ENV
 
-- name: Bump Version
-  uses: chkfung/android-version-actions@v1.1
-  with:
-    gradlePath: app/build.gradle.kts
-    versionCode: ${{ github.run_number }}
-    versionName: ${{ env.VERSION_NAME }}
+    - name: Sign APK and create release
+      run: |
+        cd /home/runner/work/reactmap-android/reactmap-android/
+        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=/home/runner/work/reactmap-android/reactmap-android/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} -Preactmap.defaultDomain=${{ secrets.MAP_URL }} -Preactmap.packageName=${{ env.PACKAGE_NAME }}
 
-- name: Run Linters and Test
-  run: ./gradlew check
+    - name: List APK directory - apk
+      run: ls -R /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/
+      
+    - name: Upload Artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: Reactmap-android
+        path: /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/app-release.apk
 
-- name: Upload Reports
-  uses: actions/upload-artifact@v2
-  with:
-    name: Test-Reports
-    path: app/build/reports
-  if: always()
+    - name: Rename Artifact
+      run: mv /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/app-release.apk /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/${{ secrets.APP_NAME }}-v${{ env.VERSION_NAME }}.apk
 
-- name: Restore playstore.keystore.jks
-  run: echo $KEYSTORE_FILE | base64 -d > /keystore.jks
 
-./gradlew assembleRelease \
- -Pandroid.injected.signing.store.file=$KEYSTORE_FILE \
- -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
- -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
- -Pandroid.injected.signing.key.password=$KEY_PASSWORD \
+    - name: Release with ncipollo/release-action
+      id: release
+      uses: ncipollo/release-action@v1
+      with:
+        artifacts: /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/${{ secrets.APP_NAME }}-v${{ env.VERSION_NAME }}.apk
+        token: ${{ secrets.GITHUB_TOKEN }}
+        generateReleaseNotes: true
+        skipIfReleaseExists: true
+        tag: v${{ env.VERSION_NAME}}
 
-- name: Release
-  id: create_release
-  uses: actions/create-release@v1
-  with:
-    release_name: Release v.${{ env.VERSION_NAME }}
-    draft: false
-    prerelease: false
-  env:
-    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Send Discord webhook notification
+      if: env.DISCORD_WEBHOOK_URL && steps.release.outputs.release_created == 'true'
+      run: |
+        release_url="https://github.com/${{ github.repository }}/releases/tag/v${{ env.VERSION_NAME }}"
+        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"New release v${{ env.VERSION_NAME }} is available! [View Release]($release_url)\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
+      env:
+        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
